feature: add dashboard cta to docs
cypress-io/cypress-documentation pull request #3103
Opened 2020-08-25 17:11 UTC by bencodezen

2020-08-25 17:42 UTC, amirrustam commented
Posting screenshots here as part of the review. Currently, this is how desktop and mobile look like:

Desktop:
<img width="1902" alt="Screen Shot 2020-08-25 at 1 40 05 PM" src="https://user-images.githubusercontent.com/334337/91208783-b90a3600-e6d8-11ea-982e-6ce6df8c5ffc.png">

Mobile:
<img width="497" alt="Screen Shot 2020-08-25 at 1 40 26 PM" src="https://user-images.githubusercontent.com/334337/91208794-bd365380-e6d8-11ea-8e90-fbacaa7229a6.png">

2020-08-26 08:15 UTC, jennifer-shehane requested changes
Agree with Amir that there needs to be some padding above it cause it seems smushed up to the content. 

The screenshot quality is really poor. All of it is fuzzy on my screen. Would like a better quality screenshot.

<img width="1638" alt="Screen Shot 2020-08-26 at 2 43 42 PM" src="https://user-images.githubusercontent.com/1271364/91278865-c42d9680-e7aa-11ea-95ef-746a332bebdf.png">

2020-08-26 08:15 UTC, jennifer-shehane commented on themes/cypress/layout/partial/dashboard-cta.swig
> +      <li>See exact point of failure of tests running in CI</li>
```suggestion
      <li>See the exact point of failure of tests running in CI</li>
```

2020-08-27 18:31 UTC, jordanjwoods commented
@amirrustam @bencodezen what do we need to do to push this through? Do I need to get a high-res image?

2020-08-28 14:19 UTC, bencodezen commented
@amirrustam @jennifer-shehane 

I've updated the spacing above the CTA. Good recommendation!

<img width="1344" alt="Screen Shot 2020-08-28 at 10 15 27 AM" src="https://user-images.githubusercontent.com/4836334/91578158-ceb96e80-e917-11ea-890a-980ce4a5661a.png">

To account for the screenshot resolution issue, I'm proposing to remove it on mobile at this point so we can get out an iteration of it since it's less noticeable on desktop.

<img width="532" alt="Screen Shot 2020-08-28 at 10 16 38 AM" src="https://user-images.githubusercontent.com/4836334/91578223-e0027b00-e917-11ea-95dc-31e7f747f501.png">

@jordanjwoods Would love your thoughts on this when you have a moment too!

2020-08-28 14:38 UTC, jordanjwoods commented
@bencodezen I support the change! Also, I've reached out to our designer about getting higher res image assets.

2020-08-28 15:41 UTC, amirrustam commented
Great, after getting hi-res image and resolving failing tests, this is good to go.

2020-08-28 16:48 UTC, jordanjwoods commented
@bencodezen I received a 300ppi and 150ppi version of the assets from our designer. Can you see if these will work? 
![150ppi](https://user-images.githubusercontent.com/56408819/91592580-bf90eb80-e92c-11ea-9bcb-a32e77159762.png)
![300ppi](https://user-images.githubusercontent.com/56408819/91592581-bf90eb80-e92c-11ea-94e4-3f0af7ef58f2.png)

2020-08-31 18:54 UTC, merged