Added mention about lack of default method
cypress-io/cypress-documentation pull request #3213
Opened 2020-10-02 17:47 UTC by JonahKK

One difference that was not described before. Took me a moment to find out why my migration to `route2` failed ;).

2020-10-02 17:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress-documentation?pullRequest=3213) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress-documentation?pullRequest=3213) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress-documentation?pullRequest=3213) it.</sub>

2020-10-06 07:53 UTC, jennifer-shehane requested changes
@JonahKK The method should match `GET` by default as mentioned in this section: https://docs.cypress.io/api/commands/route2.html#routeMatcher-RouteMatcher

Can you give an example of the unexpected behavior you encountered? We'd love to update the docs to be more helpful.

2020-10-06 08:40 UTC, JonahKK commented
@jennifer-shehane Okay, so it might be a defect then. But before I report anything, could you check this case:
Our app uses external API, because of CORS, before making GET request, app sends OPTIONS request. Now, when I don't include method in `route2` it matches both requests. You can see on the screenshots, that there is also a `validate_name` alias, that is matched just once, but `route2` responsible for spying it, has method specified.
![2020-10-06_10h36_46](https://user-images.githubusercontent.com/23238398/95178887-39d04d80-07c0-11eb-9ade-7fb68c994879.png)
![2020-10-06_10h36_53](https://user-images.githubusercontent.com/23238398/95178892-3a68e400-07c0-11eb-8fb2-91555b2f690c.png)

2020-10-13 08:45 UTC, jennifer-shehane commented
The documentation for this was incorrect. It does not match `GET` by default, and instead matches `*`, so any method. This doc has been fixed here: https://github.com/cypress-io/cypress-documentation/pull/3235

2020-10-13 08:57 UTC, JonahKK commented
So this PR was about this difference. But in my PR the difference was mentioned in `Comparison to cy.route()` section as this change makes `cy.route2` different from `cy.route`.

2020-10-19 09:04 UTC, jennifer-shehane commented
Yah, ok I can see that.

2020-10-19 09:06 UTC, jennifer-shehane approved these changes

2020-10-19 09:06 UTC, merged