Added exploring cypress and its features blog
cypress-io/cypress-documentation pull request #3328
Opened 2020-11-13 17:08 UTC by alapanme

2020-11-13 17:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress-documentation?pullRequest=3328) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress-documentation?pullRequest=3328) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress-documentation?pullRequest=3328) it.</sub>

2020-11-16 08:42 UTC, jennifer-shehane requested changes
The blog post entry is referencing an image located at `source/img/examples/exploring-cypress and-its-features.jpg`, but there is no image actually located there. The provided image should be of size `715×480`.

2020-11-16 08:43 UTC, jennifer-shehane commented
Can you add the image from https://github.com/cypress-io/cypress-documentation/pull/3327 to this PR?

2020-11-16 09:08 UTC, alapanme commented
Hi Jennifer, I have updated the image in the correct location with the required dimensions.

2020-11-20 12:42 UTC, jennifer-shehane approved these changes

2020-11-20 12:42 UTC, merged