docs: note experimentalFetchPolyfill as deprecated
cypress-io/cypress-documentation pull request #3330
Opened 2020-11-16 19:52 UTC by flotwig

for https://github.com/cypress-io/cypress/pull/9215

2020-11-18 06:28 UTC, jennifer-shehane requested changes
We need to update this warning also in the cy.route() page - just assuming we shouldn't recommend a deprecated API. Do you have any recommendations for wording on this warning for this release? 

<img width="877" alt="Screen Shot 2020-11-18 at 12 57 35 PM" src="https://user-images.githubusercontent.com/1271364/99493486-ad5ba200-299d-11eb-999b-7ef783298471.png">

2020-11-18 20:01 UTC, flotwig commented
@jennifer-shehane updated, lmk your thoughts

2020-11-19 02:21 UTC, jennifer-shehane approved these changes

2020-11-19 02:21 UTC, jennifer-shehane commented on source/_partial/network_stubbing_warning.md
> +Cypress also has a new [cy.http()](/api/commands/http.html) command that supports requests using the Fetch API and other types of network requests like page loads. For more information, check out the
```suggestion
Cypress also has a new [`cy.http()`](/api/commands/http.html) command that supports requests using the Fetch API and other types of network requests like page loads. For more information, check out the [`cy.http()` documentation](/api/commands/http.html).{% endnote %}
```

2020-11-19 03:14 UTC, merged