Update typescript docs for adding custom commands
cypress-io/cypress-documentation pull request #3471
Opened 2021-01-08 06:37 UTC by kaspatel-mdsol

This is a PR to update documentation for adding custom commands in typescript that may or may not include external modules.

This is originally sourced from [here](https://github.com/cypress-io/add-cypress-custom-command-in-typescript/issues/2#issuecomment-389870033).

2021-01-08 06:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress-documentation?pullRequest=3471) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress-documentation?pullRequest=3471) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress-documentation?pullRequest=3471) it.</sub>

2021-01-08 07:05 UTC, jennifer-shehane commented
@kaspatel-mdsol Thanks for the contribution! Could you please sign our CLA?

2021-02-05 13:33 UTC, bahmutov commented on source/guides/tooling/typescript-support.md
> +    "baseUrl": "./",
why do you need to set the base URL?

2021-02-05 13:34 UTC, bahmutov commented on source/guides/tooling/typescript-support.md
> +import { MyModule } from "@foo/bar";
I really do not like foo / bar example here. What does MyModule do?

2021-02-05 13:34 UTC, bahmutov requested changes
I am not sure how this documentation update is any better than the previous doc

2021-02-22 23:35 UTC, amirrustam commented
@kaspatel-mdsol feel free to reopen this PR if you can address @bahmutov's feedback.

2021-02-22 23:35 UTC, closed without merging