add common problems section to the configuration reference
cypress-io/cypress-documentation pull request #3483
Opened 2021-01-12 14:25 UTC by bahmutov

with `baseUrl` inside the `env` block

<img width="850" alt="Screen Shot 2021-01-12 at 9 24 58 AM" src="https://user-images.githubusercontent.com/2212006/104326818-249e4580-54b8-11eb-8bb5-1be4a7a415e6.png">

2021-01-13 04:07 UTC, jennifer-shehane requested changes
I think it's generally a bad idea to put non-working example in code in the docs. People do not read and I've seen them copy non-working examples before. 

I'm kind of not a fan of documenting every way that you could write Cypress wrong in general.

2021-01-27 19:26 UTC, bahmutov commented
I think this is an acceptable approach: clearly marking the problematic way. At least the users can see that. I would rather have something we can reply with when the base URL is set incorrectly, that respond by writing the same text again and again and again.

<img width="616" alt="Screen Shot 2021-01-27 at 2 25 01 PM" src="https://user-images.githubusercontent.com/2212006/106042746-77c4ea80-60ab-11eb-8f2c-b896e9eaa9b0.png">

2021-01-27 19:42 UTC, bahmutov commented
I updated the description to make "will not work" vs "the correct way" more prominent

2021-02-03 01:38 UTC, jennifer-shehane approved these changes

2021-02-04 15:01 UTC, merged