add section on types of tests
cypress-io/cypress-documentation pull request #3896
Opened 2021-04-28 20:29 UTC by bahmutov

because I hear this question again and again and it would be nice to clarify it once and for all

https://github.com/cypress-io/cypress/discussions/16074

2021-04-28 20:30 UTC, bahmutov commented on content/guides/core-concepts/writing-and-organizing-tests.md
> +## Folder structure
every other 2 word heading here is lowercase

2021-05-03 20:51 UTC, jennifer-shehane requested changes
I added some sections so that it's clearer to glance through the type of tests. I feel like this would be better in the 'Why Cypress" page. The introduction page is already pretty intimidating. 

I dunno. Thoughts?

2021-05-04 11:55 UTC, bahmutov commented
Sure, I initially put it there, then moved, definitely can be in the why cypress page

2021-05-04 18:37 UTC, jennifer-shehane approved these changes

2021-05-04 20:07 UTC, merged

2021-05-06 14:51 UTC, amirrustam commented
We're currently not ready to present unit Node testing in such a manner and in such a top-level location within the docs. If there is a question about this type of content in the future, please reach out to me.

These changes will be reverted.

2021-05-06 14:54 UTC, bahmutov commented
the entire section? the users ask about this a lot, and no one understands they can do unit tests there as well, why revert? Clarify maybe, maybe remove the node unit testing, but let's keep the content there

2021-05-06 14:59 UTC, JessicaSachs commented
1. I'm fine keeping the CT content there. It's correct, doesn't confuse me, and drives adoption.
2. No opinion on API testing.
3. I agree with Amir on Node testing.

2021-05-06 15:01 UTC, amirrustam commented
To clarify, I'm just referring to the unit/node testing section.