[Typescript] Add a note to combine types & custom command for auto types
cypress-io/cypress-documentation pull request #3906
Opened 2021-05-03 17:02 UTC by elevatebart

2021-05-03 19:48 UTC, elevatebart commented
I could as well transform this documentation to have the merged files as the main explanation.
It is a change, but would really help our users I believe.

2021-05-03 20:32 UTC, jennifer-shehane requested changes
There's this section also in the Custom commands section:

>If your specs files are in TypeScript, you should include the TypeScript definition file, `cypress/support/index.d.ts`, with the rest of the source files.

This makes it sound like I have to do an extra step, like an 'include'. But it seems like my TS is working for my custom command without doing anything else? I would remove this line if it's no longer necessary.

2021-05-03 20:32 UTC, jennifer-shehane commented on content/guides/tooling/typescript-support.md
> +```typescript
This area appears to be addressing JS specifically, which is why the example had the triple slash references, but I do think this is likely confusing people. I would remove this paragraph "Even if your project is Javascript only....". The doc is about TypeScript after all.

2021-05-04 23:35 UTC, elevatebart commented
Thank you @jennifer-shehane,

I updated the docs to include your remarks. 
I think I should as well add a link to here from the [custom commands docs](https://docs.cypress.io/api/cypress-api/custom-commands#See-also)

2021-05-04 23:45 UTC, elevatebart commented
It is now linked !

2021-05-05 15:15 UTC, jennifer-shehane approved these changes

2021-05-05 15:15 UTC, jennifer-shehane commented on content/api/cypress-api/custom-commands.md
> +- See how to add Typescript support in the documentation [Types for custom commands](/guides/tooling/typescript-support#Types-for-custom-commands)
```suggestion
- See how to add [TypeScript support for custom commands](/guides/tooling/typescript-support#Types-for-custom-commands)
```

2021-05-05 15:29 UTC, merged