DX-313 Missing content for error, "Whoops, we can't run your tests."
cypress-io/cypress-documentation pull request #4016
Opened 2021-07-08 17:13 UTC by mccataldo

Closes DX-313

2021-07-12 13:22 UTC, robertguss approved these changes

2021-07-12 14:57 UTC, cowboy requested changes

2021-07-12 14:57 UTC, cowboy commented on content/guides/references/error-messages.md
> +See [Cypress detected policy settings on your computer that may cause issues](#Cypress-detected-policy-settings-on-your-computer-that-may-cause-issues) below.
I'd like to see us go into a little more depth here. Per @flotwig this error can be seen when any of the following occur:

* a policy blocks the extension/proxy settings
* a plugin breaks the `--proxy-server` or `--load-extension` arguments
* the user visits the Cypress proxy URL outside of a Cypress browser

The first bullet seems to be covered here, but not the other two.

2021-07-13 15:05 UTC, cowboy commented
Superseded by #4021

2021-07-13 15:05 UTC, closed without merging