8.2.0 Release
cypress-io/cypress-documentation pull request #4049
Opened 2021-07-29 14:45 UTC by jennifer-shehane

Targeted release date 8/2/2021

- [ ] Changelog
- [ ] Sessions
- [ ] XHR logging updates

2021-08-03 19:18 UTC, cowboy requested changes

2021-08-03 19:18 UTC, cowboy commented on content/_changelogs/8.2.0.md
> +  [our blog](https://cypress.io/blog/2021/08/02/authenticate-faster-in-tests-cy-session-command/)
```suggestion
  [our blog](https://cypress.io/blog/2021/08/03/authenticate-faster-in-tests-cy-session-command/)
```

2021-08-04 13:59 UTC, jennifer-shehane commented on content/_changelogs/8.2.0.md
> +    [#14843](https://github.com/cypress-io/cypress/issues/14843).
Thanks for the update. This seems much more comprehensive. I wasn't aware of the change to the circles actually.

2021-08-04 19:20 UTC, flotwig approved these changes

2021-08-04 19:20 UTC, merged