Add page for Cypress.currentTest
cypress-io/cypress-documentation pull request #4052
Opened 2021-08-02 20:17 UTC by jennifer-shehane

Add page to explain what Cypress.currentTest does technically. 

I’d love this to have better examples of *why* someone would use this. Could likely look at https://github.com/cypress-io/cypress/issues/2972 for examples.

2021-08-02 20:38 UTC, chrisbreiding commented on content/api/cypress-api/currenttest.md
> +Cypress.currentTest.titlePath
```suggestion
// an object with title and titlePath properties
Cypress.currentTest

// the title of the current test
Cypress.currentTest.title

// an array with the current test's title path
Cypress.currentTest.titlePath
```

I feel like using `returns` indicates they are functions instead properties.

2021-08-02 20:40 UTC, chrisbreiding requested changes

2021-08-02 20:40 UTC, chrisbreiding commented on content/api/cypress-api/currenttest.md
> +`Cypress.currentTest` returns the currently executing test instance with
```suggestion
`Cypress.currentTest` is an object representing the currently executing test instance, with
```

2021-08-02 20:40 UTC, cowboy requested changes
Looks good. One minor request.

2021-08-02 20:40 UTC, cowboy commented on content/api/cypress-api/currenttest.md
> +
Can we add a note to this effect?

```suggestion

<Alert type="warning">

Note that `Cypress.currentTest` may only be used inside tests and [test
hooks](/guides/core-concepts/writing-and-organizing-tests#Hooks),
and will be `null` outside of tests and test hooks.

</Alert>
```

2021-08-02 20:41 UTC, jennifer-shehane commented on content/api/cypress-api/currenttest.md
> +
Ah, great point to add!

2021-08-02 21:25 UTC, cowboy requested changes

2021-08-02 21:25 UTC, cowboy commented on content/api/cypress-api/currenttest.md
> +## Syntax
Whoops, these need a linebreak between them

```suggestion
</Alert>

## Syntax
```

2021-08-03 13:56 UTC, chrisbreiding approved these changes

2021-08-03 13:57 UTC, merged