UNIFY-327 Update all plugin file examples
cypress-io/cypress-documentation pull request #4102
Opened 2021-09-21 20:10 UTC by jaffrepaul

https://cypress-io.atlassian.net/browse/UNIFY-327

2021-09-23 18:24 UTC, jaffrepaul commented on content/api/commands/task.md
> +:::cypress-plugin-example
Let's confirm this is what we want here since the example changed a bit with the new directive.

2021-09-23 21:08 UTC, cowboy requested changes
Overall, looks good. Take a look at the comments and LMK if you have any questions!

2021-09-23 21:08 UTC, cowboy commented on content/guides/component-testing/framework-configuration.md
> +:::cypress-plugin-example
The directive needs to be updated to support an attribute that allows us to specify the config property that `setupNodeEvents` displays in. Right now, it's hard-coded to `e2e` but some examples will need it to be `component`. We'll also need an attribute to suppress the `setupNodeEvents can be defined in either the e2e or component configuration` comment.

See the `include` directive source for an example of using attributes.

So changing the above line to this:

```
:::cypress-plugin-example {configProp=component noComment=true}
```

should render like this:

```js
const { defineConfig } = require('cypress')
const injectDevServer = require('@cypress/react/plugins/react-scripts')

module.exports = defineConfig({
  component: {
    setupNodeEvents(on, config) {
      injectDevServer(on, config)
      
      return config
    }
  }
})
```

But any existing examples without those attributes should continue to render as-is.

Once that's done, please update all the examples in this file and the content/guides/component-testing/introduction.md file to use the `{configProp=component noComment=true}` attributes.

2021-09-23 21:08 UTC, cowboy commented on content/guides/references/configuration.md
> +:::cypress-plugin-example
Please revert the changes in this file for now and add a note to UNIFY-366.

2021-09-23 21:36 UTC, jaffrepaul commented on content/api/cypress-api/env.md
> +  process.env.NODE_ENV === 'qa' ? 'hoop brick tort' : 'sushi cup lemon'
Got it. This sort of thing will be handled in UNIFY-366. Just to be clear does as-is refer to the original version or this update?

2021-09-23 21:51 UTC, cowboy commented on content/api/cypress-api/env.md
> +  process.env.NODE_ENV === 'qa' ? 'hoop brick tort' : 'sushi cup lemon'
As it currently is, with the updates you've already applied in this branch. Otherwise I'd ask you to revert your changes!

2021-09-24 21:32 UTC, jaffrepaul commented on content/api/commands/task.md
> +:::cypress-plugin-example
Wrapped the comments up in these fixes cecc092f4f4d04ec2bc24b0b48bbcf4968720671

2021-09-27 14:21 UTC, jaffrepaul commented
In case the update got lost in the comments....

Wrapped the comments up in these fixes cecc092

2021-09-27 17:29 UTC, cowboy approved these changes
LGTM!

2021-09-27 18:06 UTC, merged