Add Select By Index
cypress-io/cypress-documentation pull request #4105
Opened 2021-09-22 14:44 UTC by davidmunechika

Link to implementation: https://github.com/cypress-io/cypress/pull/18201

Updated docs to reflect new argument `index` which can be used to select an option by index within the `select()` command.

2021-09-22 14:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress-documentation?pullRequest=4105) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress-documentation?pullRequest=4105) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress-documentation?pullRequest=4105) it.</sub>

2021-09-23 18:50 UTC, jennifer-shehane commented
Updating the base branch to be against 8.5.0-release branch since this will be associated with that releaes. https://github.com/cypress-io/cypress-documentation/pull/4108

2021-09-27 13:26 UTC, chrisbreiding requested changes

2021-09-27 13:26 UTC, chrisbreiding commented on content/api/commands/select.md
>  **<Icon name="angle-right"></Icon> value** **_(String)_**
```suggestion
**<Icon name="angle-right"></Icon> value** **_(String, Number)_**
```

2021-09-27 13:38 UTC, chrisbreiding approved these changes

2021-09-27 13:38 UTC, merged