Deprecation updates for the `nodeVersion` config option
cypress-io/cypress-documentation pull request #4194
Opened 2021-11-02 17:29 UTC by mjhenkes

As a part of issue #18684, This PR updates the documentation to declare the `nodeVersion` config as deprecated as well as explain the default `system` and behaviour, to use the same node binary that was used to launch cypress from the cli.

2021-11-02 17:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress-documentation?pullRequest=4194) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress-documentation?pullRequest=4194) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress-documentation?pullRequest=4194) it.</sub>

2021-11-02 22:22 UTC, jennifer-shehane requested changes

2021-11-02 22:22 UTC, jennifer-shehane commented on content/api/plugins/writing-a-plugin.md
> +Prior to version 9.0.0, Cypress would use the version of node bundled with Cypress itself.
We don't keep notes like this in our docs for previous versions, the docs always reflect current version. In some cases we have a 'History' section in the file to explain changes

Can you update this section to reflect the truth of the new version?

2021-11-02 22:22 UTC, jennifer-shehane commented on content/guides/references/configuration.md
> +The `nodeVersion` configuration option is deprecated and will be removed in the next major release of Cypress. Please remove this option from `cypress.json`.
We always say 'future version of Cypress'. Be vague about commitments :D 

```suggestion
The `nodeVersion` configuration option is deprecated and will be removed in a future version of Cypress. Please remove this option from your configuration file.
```

2021-11-02 22:22 UTC, jennifer-shehane commented on content/guides/references/configuration.md
> +| `nodeVersion` | `system` | Can be `system` or `bundled`. If set to `system`, Cypress will try to use the same node executable that launched the cli to execute your [plugins](/guides/tooling/plugins
```suggestion
| `nodeVersion` | `system` | Can be `system` or `bundled`. If set to `system`, Cypress will try to use the same Node version that launched Cypress to execute your [plugins](/guides/tooling/plugins-guide). If that can't be determined, Cypress will use the Node version bundled with Cypress. If set to `bundled` Cypress will use the version bundled with Cypress |
```

2021-11-03 22:30 UTC, emilyrohrbough approved these changes

2021-11-04 16:24 UTC, jennifer-shehane approved these changes
Just reread through the 'writing a plugins' page and it doesn't make sense to have this alert anymore I think, so I just removed the whole section. Looks good, we'll merge this into 9.0 as soon as the code PR is merged.

2021-11-04 18:46 UTC, merged