CLOUD-295: Add analytics aspect to "Why Cypress -> Our mission"
cypress-io/cypress-documentation pull request #4283
Opened 2021-12-20 21:14 UTC by debrisapron

This, possibly contentious, change adds language to the Our Mission section that emphasizes the analysis of test results as a key differentiator of Cypress in general, and by inference the dashboard specifically. I've tried to suggest a more general mission of leveraging test metadata to achieve a higher level of software refinement, hopefully it hasn't just degenerated into word salad.

Note also that I have added the new content to one of the existing paragraphs rather than create a new one. This is purely a subjective, aesthetic preference on my part. I felt that this content could be considered an addendum to or refinement of the language in that para.

2022-01-31 22:42 UTC, amirrustam requested changes

2022-01-31 22:42 UTC, amirrustam commented on content/guides/overview/why-cypress.md
> +generate actionable insights into long-term stability, and identify areas for
"into" or "for" ?

2022-08-11 14:07 UTC, pstakoun commented on content/guides/overview/why-cypress.md
> +want to elevate the art of software development by leveraging test results to
@brian-mann update to mission content- thoughts?

2022-10-15 01:44 UTC, pstakoun commented
@debrisapron can you get @brian-mann's input before merging please?

2022-10-17 15:27 UTC, brian-mann commented on content/guides/overview/why-cypress.md
> +improvement.
```suggestion
generate actionable insights for long-term stability by proactively identifying
areas for improvement.
```

2022-10-17 15:28 UTC, brian-mann commented on content/guides/overview/why-cypress.md
> +want to elevate the art of software development by leveraging test results to
```suggestion
aim to elevate the art of software development by leveraging test results to
```

2022-10-20 21:55 UTC, pstakoun approved these changes
Please ensure @brian-mann approves before merging

2022-10-21 00:35 UTC, debrisapron commented
@brian-mann let's do this 🚀

2022-10-24 16:29 UTC, merged