docs: update mount partial for new imports
cypress-io/cypress-documentation pull request #4426
Opened 2022-04-07 21:22 UTC by elylucas

2022-04-11 19:44 UTC, jaffrepaul approved these changes
LGTM 🎉

2022-04-12 18:50 UTC, cowboy requested changes

2022-04-12 18:50 UTC, cowboy commented on content/partials/import-mount-functions.md
> -[@cypress/react](https://github.com/cypress-io/cypress/tree/develop/npm/react)
I'm not sure we want to call `cypress/react` a library. `@cypress/react` is a library, and `cypress` is a library, but `cypress/react` is really the `react` path under the `cypress` library.

2022-04-14 19:38 UTC, cowboy approved these changes

2022-04-14 20:08 UTC, merged