docs: update writing first test ct guide
cypress-io/cypress-documentation pull request #4429
Opened 2022-04-08 21:00 UTC by elylucas

2022-04-11 19:58 UTC, jaffrepaul commented on content/guides/getting-started/writing-your-first-component-test.md
> +### Importing the Component
'Component' should be consistent in these two section titles (mounting below) should be consistent with capitalization.

2022-04-11 19:58 UTC, jaffrepaul requested changes
Added one small punctuation comment.

2022-04-11 21:18 UTC, jaffrepaul approved these changes
LGTM 🎉

2022-04-12 18:48 UTC, cowboy approved these changes

2022-04-13 15:10 UTC, merged