UDX-195-troubleshooting-guide
cypress-io/cypress-documentation pull request #4478
Opened 2022-05-13 19:21 UTC by jaffrepaul

Adds a troubleshooting page to the CT docs to cover commonly faced issues. 

Combines:
- https://cypress-io.atlassian.net/browse/UDX-195
- https://cypress-io.atlassian.net/browse/UDX-193
- https://cypress-io.atlassian.net/browse/UDX-62

2022-05-13 19:23 UTC, jaffrepaul commented on content/guides/getting-started/component-test-troubleshooting.md
> +There are times when you will encounter errors or unexpected behavior with
Considering adding a section like this at the top as a general introduction. I just pulled this from https://docs.cypress.io/guides/references/troubleshooting but we can pull this into a partial if using the same content makes sense.

2022-05-17 15:19 UTC, elylucas requested changes
Got a few suggestions. Also, we might want to update the heading's casing to be more consistent. I opened a discussion in slack but feel free to update the headings if you like.

2022-05-17 15:30 UTC, jaffrepaul commented on content/guides/getting-started/component-test-troubleshooting.md
> +There are times when you will encounter errors or unexpected behavior with
dig it.

2022-05-17 18:39 UTC, elylucas approved these changes
🤙

2022-05-17 18:47 UTC, merged