Clarify disabling Command Log
cypress-io/cypress-documentation pull request #4655
Opened 2022-08-08 16:25 UTC by j14t

2022-08-08 19:44 UTC, marktnoonan requested changes

2022-08-08 19:44 UTC, marktnoonan commented on content/guides/references/troubleshooting.md
> +**Note:** In headless mode screenshots and videos will not include the Command
> In headless mode screenshots and videos will not include the Command Log.

Really it's in any mode: open , run headed, or run headless. No command log will render when a spec is running.


```suggestion
**Note:** With this variable set, screenshots and videos will not include the Command Log
```

2022-08-08 19:44 UTC, marktnoonan commented on content/guides/references/troubleshooting.md
> +when there is a failure you cannot see what command failed.
```suggestion
With this variable set, Cypress will skip rendering the Command Log entirely, and perform none of the usual DOM updates to display information about commands and statuses as the test runs. 
```

2022-08-08 22:12 UTC, marktnoonan approved these changes

2022-08-08 22:13 UTC, marktnoonan commented
Thanks @j14t, I approved but somebody from @cypress-io/dx should get eyes on this also before merge.

2022-08-09 16:39 UTC, jaffrepaul approved these changes
LGTM 🎉

2022-08-26 17:55 UTC, j14t commented
Can someone merge? I don't have permissions.

2022-08-26 18:53 UTC, admah commented
@j14t sorry this has taken a bit to get in. Could you see what the `lint` failure is?

2022-08-29 15:20 UTC, merged