Add section about Smart Orchestration to the Best Practices page
cypress-io/cypress-documentation pull request #4720
Opened 2022-09-08 21:09 UTC by debrisapron

This addresses #4700.

Adds a Best Practices section suggesting use of the Dashboard to reduce test duration / load.

2022-09-08 21:13 UTC, debrisapron commented
New para is here: https://cypress-documentation-224st5aeq-cypress-io.vercel.app/guides/references/best-practices#Running-Tests-Intelligently

2022-09-09 16:31 UTC, pstakoun commented on content/guides/references/best-practices.md
> +As your test suite grows & takes longer to run, you may find yourself hitting
```suggestion
As your test suite grows and takes longer to run, you may find yourself hitting
```

2022-09-09 16:31 UTC, pstakoun commented on content/guides/references/best-practices.md
> +may be shipped. This issue is compounded further if you have dependent chains of
```suggestion
performance bottlenecks on your CI system. We recommend integrating your source
control system with your test suite such that merges are blocked until all your
Cypress tests have passed. The downside of this is that longer test
execution times slow the velocity at which branches may be merged and features
may be shipped. This issue is compounded further if you have dependent chains of
```

2022-09-09 16:31 UTC, pstakoun commented on content/guides/references/best-practices.md
> +[load balancing](/guides/guides/parallelization#Balance-strategy) &
```suggestion
[load balancing](/guides/guides/parallelization#Balance-strategy), and
```

2022-09-09 16:31 UTC, pstakoun commented on content/guides/references/best-practices.md
> +[test run cancellation](/guides/dashboard/smart-orchestration#Cancel-test-run-when-a-test-fails),
Should we mention failure prioritization ([Run failed specs first](https://docs.cypress.io/guides/dashboard/smart-orchestration#Run-failed-specs-first)) here too?

2022-10-06 15:53 UTC, pstakoun commented on content/guides/references/best-practices.md
> +[running failed specs first](/guides/dashboard/smart-orchestration#Run-failed-specs-first),
there are two "and"s here

2022-10-06 15:54 UTC, pstakoun requested changes
just that double "and"

2022-10-11 01:18 UTC, pstakoun approved these changes

2022-10-11 01:19 UTC, pstakoun commented
I think it would be cool to use one of the smart orchestration/parallelization images/diagrams here to call more attention to the section, but we can improve this iteratively. lgtm

2022-10-13 18:05 UTC, merged