Add clarification that auto-cancellation happens after spec
cypress-io/cypress-documentation pull request #4961
Opened 2023-01-05 19:06 UTC by debrisapron

Resolves Jira ticket CYCLOUD-754

2023-01-05 19:08 UTC, debrisapron commented
New content preview here: https://cypress-documentation-4dcrch23b-cypress-io.vercel.app/guides/cloud/smart-orchestration#Auto-Cancellation

2023-01-05 20:26 UTC, rockhold approved these changes
LGTM 👍🏼

2023-01-06 05:27 UTC, ryanpei requested changes
minor spelling edit

2023-01-06 05:27 UTC, ryanpei commented on content/guides/cloud/smart-orchestration.md
> +over a preset threshold, the entire test run is cancelled. Note that any
```suggestion
over a preset threshold, the entire test run is canceled. Note that any
```
We've used `canceled` throughout the docs, and that aligns with American English convention.

2023-01-06 22:42 UTC, merged