cucumber stance
cypress-io/cypress-documentation pull request #5115
Opened 2023-03-13 23:34 UTC by conversayShawn

Add some verbiage around cucumber

2023-03-14 19:39 UTC, emilyrohrbough commented on docs/faq/questions/using-cypress-faq.mdx
> +## <Icon name="angle-right" /> Should I use Cucumber to write tests?
Adding a new section under `Can I use Cucumber to write tests?` feels weird. I'd just combine the answer with the above response:
```suggestion
```

2023-03-14 19:40 UTC, emilyrohrbough commented on docs/faq/questions/using-cypress-faq.mdx
> +is unique and based on the needs of the user.
```suggestion
Deciding to use Cucumber is based on the needs of the users.
```

2023-03-14 19:40 UTC, emilyrohrbough commented on docs/faq/questions/using-cypress-faq.mdx
> +_Note_
```suggestion
```

2023-03-15 20:54 UTC, elylucas requested changes
I agree with Emily's comment about not having a second question. Also was looking at the answer for the first question and I think we could summarize it all with something like:

While Cypress does not provide official support for Cucumber, you can use Cucumber through a [community plugin](link to the plugin). Using the plugin adds additional complexity to your testing workflow, so ensure your team understands the benefits and drawbacks before adopting Cucumber. 

If your team is looking to do behavior driven development, you might be interested in these articles that discuss using BDD's given/when/then syntax directly in Cypress instead of using Cucumber's scenarios:

(links you have to the blogs)

2023-03-16 20:04 UTC, conversayShawn commented on docs/faq/questions/using-cypress-faq.mdx
> +_Note_
👍🏽

2023-03-20 21:08 UTC, emilyrohrbough approved these changes

2023-03-21 16:24 UTC, elylucas approved these changes

2023-03-22 14:49 UTC, merged