chore: update .scrollIntoView() example
cypress-io/cypress-documentation pull request #5161
Opened 2023-03-31 13:47 UTC by emilyrohrbough

.scrollIntoView() is unsafe to chain further - update example to show valid example

Closes #5002 
Closes #5160

2023-03-31 13:53 UTC, emilyrohrbough commented
TODO: Needs screenshot update of the command log.

2024-12-17 09:37 UTC, MikeMcC399 commented
@emilyrohrbough

- Can this PR be revived? Documentation on https://docs.cypress.io/api/commands/scrollIntoView#Scrolling is still incorrect and issue https://github.com/cypress-io/cypress-documentation/issues/5160 remains open.

2025-07-11 14:27 UTC, MikeMcC399 commented
@marktnoonan 

It can't be merged until it is fixed to change the moved contents on https://docs.cypress.io/api/commands/scrollIntoView#Scrolling

2025-07-11 14:30 UTC, marktnoonan commented
Thanks @MikeMcC399  - I noticed that and the TODO for the screenshot of the command log (but only after I approved).

I'll tidy this up at some point today and we can get it in.

2025-07-11 14:30 UTC, marktnoonan requested changes
Just blocking while there is WIP

2025-07-11 17:03 UTC, MikeMcC399 commented
@marktnoonan 

It may be easier to close this PR and create as new one, as the changes are quite trivial and the target file has changed.

It's a bit scary seeing 300+ files changed, even if this PR is in draft!

2025-07-11 17:13 UTC, marktnoonan commented
Haha, yes, I did a suspicious rebase on my side - we'll make sure the diff is accurate one way or another before merge.

2025-09-16 12:26 UTC, MikeMcC399 commented
@marktnoonan 

This PR has not improved with age and it now shows a staggering 1488 files being changed!

I would still recommend closing and starting afresh.

2025-09-16 12:53 UTC, closed without merging