address deprecated xpath plugin references
cypress-io/cypress-documentation pull request #5287
Opened 2023-06-08 08:57 UTC by MikeMcC399

This PR moves the [xpath](https://github.com/cypress-io/cypress/tree/develop/npm/xpath) plugin reference in the [Plugins list](https://docs.cypress.io/plugins) to the [Legacy](https://docs.cypress.io/plugins#Legacy) section.

Links to [cypress-io/cypress-xpath](https://github.com/cypress-io/cypress-xpath) on other pages are removed.

## Changed pages

- [Plugins list](https://docs.cypress.io/plugins)
- [API > Custom Commands > See also](https://docs.cypress.io/api/cypress-api/custom-commands#See-also)
- [End-to-End Testing > Migrating from Other Frameworks > Migrating from Protractor to Cypress > Working with the DOM](https://docs.cypress.io/guides/end-to-end-testing/protractor-to-cypress#Working-with-the-DOM)

## Reasons

[xpath](https://github.com/cypress-io/cypress/tree/develop/npm/xpath) shows the README text "@cypress/xpath has been deprecated and is no longer supported." so for consistency with this message it should no longer be advertised in the main part of the [Plugins list](https://docs.cypress.io/plugins).

The repository [cypress-io/cypress-xpath](https://github.com/cypress-io/cypress-xpath) is deprecated and refers instead to https://github.com/cypress-io/cypress/tree/develop/npm/xpath and to https://www.npmjs.com/package/@cypress/xpath, both of which carry deprecation notices.

2023-06-08 19:12 UTC, mschile requested changes

2023-06-08 19:12 UTC, mschile commented on src/data/plugins.json
> -          "name": "cypress-xpath",
Let's move this down to the "Legacy" section instead of removing it.

2023-06-09 09:47 UTC, MikeMcC399 commented
- This PR brings up the more general question of how the [Plugins list](https://docs.cypress.io/plugins) should be maintained and what the criteria for having an entry in the [Plugins list > Legacy section](https://docs.cypress.io/plugins#Legacy) should be, so I submitted a separate issue for this https://github.com/cypress-io/cypress-documentation/issues/5293. This is something that the Cypress.io team would need to decide on.

2023-06-09 14:34 UTC, mschile approved these changes

2023-06-09 14:35 UTC, merged