docs: Cypress App Notifications
cypress-io/cypress-documentation pull request #5327
Opened 2023-06-20 05:49 UTC by lmiller1990

2023-06-20 06:34 UTC, lmiller1990 commented on docs/guides/cloud/cypress-app-integration.mdx
> +How your desktop manages notifications depends on your Linux distribution your windows manager.
I spend quite a while trying to understand how Ubuntu (Gnome) manages notifications for desktop applications not installed via Software Center. I gave up after about an hour, I can't figure it out. It uses something called `gsettings`, but the manual doesn't include any examples and all the things I tried didn't work.

Either way, out of the box every seems to work great - if a user does get stuck, we can help them out. Most non power users are going to be Ubuntu or other "easy" distributions, that just work - power users will likely know their OS better than we do and will be able to figure it out.

2023-06-20 06:44 UTC, MikeMcC399 commented on docs/guides/cloud/cypress-app-integration.mdx
> +### MacOS
```suggestion
### macOS
```

according to Apple on https://support.apple.com/macos

2023-06-20 06:45 UTC, MikeMcC399 commented on docs/guides/cloud/cypress-app-integration.mdx
> +If notifications are not showing up in MacOS, under "System Preferences" select "Notifications" and choose "Cypress":
```suggestion
If notifications are not showing up in macOS, under "System Preferences" select "Notifications" and choose "Cypress":
```

2023-06-20 06:45 UTC, MikeMcC399 commented on docs/guides/cloud/cypress-app-integration.mdx
> +  alt="Notification in System Preferences for MacOS"
```suggestion
  alt="Notification in System Preferences for macOS"
```

2023-06-20 06:45 UTC, MikeMcC399 commented on docs/guides/cloud/cypress-app-integration.mdx
> +Notifications for Windows is currently not supported. Supported will be added in a later release.
```suggestion
Notifications for Windows is currently not supported. Support will be added in a later release.
```

2023-06-20 06:46 UTC, MikeMcC399 requested changes
Typo suggestions added in-line.

2023-06-20 06:52 UTC, lmiller1990 commented
> Typo suggestions added in-line.

That was fast, thank you! 💯

2023-06-20 06:59 UTC, MikeMcC399 commented
@lmiller1990 

You're welcome! You also need to run linting.

2023-06-20 11:13 UTC, MikeMcC399 commented on docs/guides/cloud/cypress-app-integration.mdx
> +How your desktop manages notifications depends on your Linux distribution your windows manager.
Not sure about this sentence:
"How your desktop manages notifications depends on the windows manager of your Linux distribution"
perhaps?

2023-06-20 18:05 UTC, jordanpowell88 requested changes
Just a few small fixes. Overall good job outlining this with quality screenshots

2023-06-20 18:05 UTC, jordanpowell88 commented on docs/guides/cloud/cypress-app-integration.mdx
> +please file an issue including the operating system and version.
We should put a link here to the issue.... I'm assuming we want this one https://github.com/cypress-io/cypress/issues/new/choose

2023-06-30 19:03 UTC, warrensplayer commented
The work in this PR is being considered if it will be incorporated into the work done with this PR: https://github.com/cypress-io/cypress-documentation/pull/5348

2023-07-11 06:28 UTC, lmiller1990 commented
We've got docs live already for this: https://docs.cypress.io/guides/cloud/recorded-runs#Notifications

I think this is fine for now. If we have people asking questions or getting confused, we can definitely revisit and update them.

2023-07-11 06:28 UTC, closed without merging