docs: branch review GA updates
cypress-io/cypress-documentation pull request #5505
Opened 2023-09-27 19:30 UTC by jaffrepaul

2023-09-27 19:39 UTC, pstakoun requested changes

2023-09-27 19:39 UTC, pstakoun commented on docs/guides/cloud/branch-review.mdx
> +"Overview" is the default view of the **Branches** tab for projects with linked GitHub repositories via our GitHub integration.
* not just projects with GH integration – for all projects now
* I'd say default view "for a branch"

2023-09-27 19:39 UTC, pstakoun commented on docs/guides/cloud/branch-review.mdx
> +"Runs" provides a list filtered by the selected branch for projects without linked repositories or those with an unknown branch. An unkown branch is one in which Cypress does not have access to the l
Runs provides a list of all runs on the current branch (in all cases). Nothing to do with linking repos or unknown branches.

2023-09-27 19:39 UTC, pstakoun commented on docs/guides/cloud/branch-review.mdx
> +If a branch PR is missing a CI run, you may also find helpful banners indicating the status and how it can be rectified.
Docs should do the heavy lifting around "how to rectify". We should communicate that if a run is missing on either the merge base or feature commit of the PR, then the banner will specify which commit is missing the run and link out to it. Recording exactly one run for every commit is the best/only way to ensure complete and accurate comparisons.

2023-09-27 21:14 UTC, tbiethman commented on docs/guides/cloud/branch-review.mdx
> +"Review" will lead to the latest available Branch Review.
@pstakoun @jaffrepaul  thoughts on expanding this a bit?

```suggestion
"Review" provides the detailed Branch Review insights for the branch's available pull requests, with the latest pull request selected by default.
```

2023-09-27 21:18 UTC, tbiethman commented on docs/guides/cloud/branch-review.mdx
> +"Runs" provides a list filtered by the selected branch for projects without linked repositories or those with an unknown branch. An unkown branch is one in which Cypress does not have access to the l
Yeah maybe something as simple as this would work:

```suggestion
"Runs" provides a list of all runs that are attributed to the branch.
```

2023-09-28 14:37 UTC, jaffrepaul commented
> The updates look good to me. @pstakoun anything stick out to you at this point?
> 
> The [branch-review-views.png](https://github.com/cypress-io/cypress-documentation/pull/5505/files#diff-b0b97a24a21dba5213514985d8a434d148bff675ecb58e128b7afbe75213e2ea) image looks like it has the shadow from the macOS dock layered on the bottom. Not sure how noticeable it'd be on the actual doc site but might be worth snapping a new one sans-shadow.

That's funny about the image. I noticed that as well. I just started using a new tool recommended by Design for better annotations, etc. Let me see if I can circle back and clean that up.

2023-09-28 15:19 UTC, pstakoun approved these changes
lgtm - I noticed the shadow in the image too

2023-09-28 15:20 UTC, pstakoun commented
cc @Jess-Cypress

2023-09-28 16:15 UTC, jaffrepaul commented
kk, I fixed the overview screenshot

2023-09-28 16:27 UTC, merged