chore: Add reroutes for routes linked from outside blogs to real URLs
cypress-io/cypress-documentation pull request #5611
Opened 2024-01-18 16:19 UTC by jennifer-shehane

Based on https://docs.google.com/spreadsheets/d/17u7EsUQNPjHntfqAFPLzEjiIyDMIwU5SVMYEADjLcUQ/edit#gid=0

2024-01-18 19:01 UTC, jaffrepaul requested changes
Just a few tiny questions/comments

2024-01-18 19:01 UTC, jaffrepaul commented on netlify.toml
> +[[redirects]]
Not sure if there's a quick way to test this, but would the previous entry suffice without another including the trailing slash?

2024-01-19 16:24 UTC, jennifer-shehane commented on netlify.toml
> +[[redirects]]
Yah I didn't want to do any deep linking because that's more likely to get out of date.

2024-01-19 16:25 UTC, jennifer-shehane commented on netlify.toml
> +[[redirects]]
Addressed [`d22a9b3` (#5611)](https://github.com/cypress-io/cypress-documentation/pull/5611/commits/d22a9b3e61a0e199ab02297f326386fae40e5532)

2024-01-19 16:37 UTC, jaffrepaul approved these changes
LGTM 🎉

2024-01-19 16:38 UTC, merged