Draft content for our Enterprise Reporting release
cypress-io/cypress-documentation pull request #5806
Opened 2024-04-15 15:54 UTC by danjohansenconsulting

New functionality that is being provided for embedded dashboard reporting and data download.  Available to our Enterprise customers.   A separate PR will be issued for the Enterprise API page where data can be programmatically retrieved.

We are anticipating a launch date of tomorrow, April 16, so that is the timeline we'll be looking to finalize and publish this change.

2024-04-15 16:16 UTC, MikeMcC399 commented on docs/guides/cloud/analytics/enterprise-reporting.mdx
> +Suite", etc. When the page first loads, data is displayed for all of the current month and the preceeding
```suggestion
Suite", etc. When the page first loads, data is displayed for all of the current month and the preceding
```

https://www.merriam-webster.com/dictionary/preceding

2024-04-15 16:16 UTC, MikeMcC399 commented on docs/guides/cloud/analytics/enterprise-reporting.mdx
> +All of the charts shown in Enteprise Reporting allow you to download the raw data used to
```suggestion
All of the charts shown in Enterprise Reporting allow you to download the raw data used to
```

2024-04-15 16:18 UTC, MikeMcC399 requested changes
Typos

2024-04-15 16:52 UTC, MikeMcC399 approved these changes
typos are fixed. thanks!

2024-04-15 20:07 UTC, MikeMcC399 commented on docs/guides/cloud/analytics/enterprise-reporting.mdx
> +of formats. And if you prefer to programatically retrieve test data for use within your own analytics
```suggestion
of formats. And if you prefer to programmatically retrieve test data for use within your own analytics
```

Elsewhere in this repo and on https://www.merriam-webster.com/dictionary/programmatically it's spelled with two m characters.

2024-04-16 13:37 UTC, elevatebart approved these changes

2024-04-17 23:01 UTC, merged