Add documentation for Cypress Test Data Generator plugin
cypress-io/cypress-documentation pull request #5938
Opened 2024-09-26 23:28 UTC by khawjaahmad

2024-09-26 23:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress-documentation?pullRequest=5938) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress-documentation?pullRequest=5938) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress-documentation?pullRequest=5938) it.</sub>

2024-09-27 13:19 UTC, jennifer-shehane requested changes

2024-09-27 13:19 UTC, jennifer-shehane commented on src/data/plugins.json
> +          "link": "https://github.com/yourusername/cypress-test-data-generator",
@khawjaahmad This link does not work. Can you link to the plugin?

2024-09-28 15:08 UTC, MikeMcC399 commented
@khawjaahmad 

I noticed some issues with your repository 
- https://github.com/khawjaahmad/cypress-test-data-generator

and your published package
- https://www.npmjs.com/package/cypress-test-data-generator

so I will open some issues in your repo to help you fix the issues.

As far as your entry in the [Plugins > Development Tools](https://docs.cypress.io/plugins#development-tools) section of the Cypress Documentation is concerned, you should move it to the end of the Community list and before the Deprecated list, as mentioned in the guide [CONTRIBUTING](https://github.com/cypress-io/cypress-documentation/blob/main/CONTRIBUTING.md#adding-plugins)

> Plugins are listed in the following order:
>
> - official (Cypress owned)
> - verified (community owned and verified by Cypress)
> - community (community owned and unverified)
> - deprecated (npm registry missing, source repo archived or incompatible with v10+)

2024-09-28 15:35 UTC, MikeMcC399 commented
The issues which need addressing are listed above.

2024-09-29 14:20 UTC, khawjaahmad commented
@MikeMcC399 

I have done the changes as requested and marked the issues closed. Also updated the plugin entry in the correct order.
Thanks

2024-09-30 05:14 UTC, khawjaahmad reviewed
changes addressed.

2024-09-30 05:35 UTC, MikeMcC399 commented
@khawjaahmad 

> I have done the changes as requested and marked the issues closed. Also updated the plugin entry in the correct order. 

Thank you for the confirmation. Your npm module now looks in good shape.

You will need to wait for re-review by the Cypress.io team now. (As an external contributor I don't have privileges to merge your content.)

2024-10-01 15:11 UTC, jennifer-shehane approved these changes

2024-10-01 15:11 UTC, merged