14.0 Docs
cypress-io/cypress-documentation pull request #5964
Opened 2024-10-24 16:36 UTC by jennifer-shehane

# DO NOT MERGE

Dependent on https://github.com/cypress-io/cypress/pull/30305 being released

2025-01-08 13:24 UTC, MikeMcC399 commented on docs/app/references/changelog.mdx
> +- Removed some component testing API stubs that were removed in [Cypress v11.0.0](https://docs.cypress.io/app/references/migration-guide#Component-Testing-Updates). Addressed in [#30696](https://gith
```suggestion
- Removed some component testing API stubs that were removed in [Cypress v11.0.0](/app/references/migration-guide#Component-Testing-Updates). Addressed in [#30696](https://github.com/cypress-io/cypress/pull/30696). Addresses [#30623](https://github.com/cypress-io/cypress/issues/30623).
```

2025-01-09 17:03 UTC, AtofStryker commented on docs/app/references/changelog.mdx
> +_Released 1/7/2024_
just a reminder to change the date

2025-01-15 16:41 UTC, AtofStryker requested changes

2025-01-15 16:41 UTC, AtofStryker commented on docs/app/references/changelog.mdx
> +_Released 1/7/2024_
```suggestion
_Released 1/16/2025_
```

2025-01-15 17:12 UTC, AtofStryker approved these changes

2025-01-15 17:18 UTC, MikeMcC399 commented on docs/app/references/changelog.mdx
> +- It is no longer possible to make a `fetch` or `XMLHttpRequest` request from the `about:blank` page in Electron (i.e. `cy.window().then((win) => win.fetch('<some-url>'))`). You must use `cy.request`
Text and link disagree.
`Addressed in [#29547](https://github.com/cypress-io/cypress/pull/30394).`

2025-01-15 17:22 UTC, MikeMcC399 commented on docs/app/references/changelog.mdx
> +- The `experimentalJustInTimeCompile` configuration option for component testing has been replaced with a `justInTimeCompile` option that is `true` by default. This option will only compile resources
```suggestion
- The `experimentalJustInTimeCompile` configuration option for component testing has been replaced with a `justInTimeCompile` option that is `true` by default. This option will only compile resources directly related to your spec, compiling them 'just-in-time' before spec execution. This should result in improved memory management and performance for component tests in `cypress open` and `cypress run` modes, in particular for large component testing suites. `justInTimeCompile` is now only supported for [`webpack`](https://www.npmjs.com/package/webpack). Addresses [#30234](https://github.com/cypress-io/cypress/issues/30234). Addressed in [#30641](https://github.com/cypress-io/cypress/pull/30641).
```

`30402` was superseded by `30641`

2025-01-15 17:26 UTC, MikeMcC399 commented on docs/app/references/changelog.mdx
> +- `@cypress/webpack-dev-server` no longer supports `webpack-dev-server` version 3. Additionally, `@cypress/webpack-dev-server` now ships with `webpack-dev-server` version 5 by default. `webpack-dev-s
```suggestion
- `@cypress/webpack-dev-server` no longer supports `webpack-dev-server` version 3. Additionally, `@cypress/webpack-dev-server` now ships with `webpack-dev-server` version 5 by default. `webpack-dev-server` version 4 will need to be installed alongside Cypress if you are still using `webpack` version 4. Addresses [#29308](https://github.com/cypress-io/cypress/issues/29308), [#30347](https://github.com/cypress-io/cypress/issues/30347), and [#30141](https://github.com/cypress-io/cypress/issues/30141).
```

https://www.merriam-webster.com/dictionary/alongside

2025-01-15 17:32 UTC, MikeMcC399 commented on docs/app/references/changelog.mdx
> +- Elements with `display: contents` will no longer use box model calculations for visibility, and correctly show as visible when it is visible. Fixed in [#29680](https://github.com/cypress-io/cypress
```suggestion
- Elements with `display: contents` will no longer use box model calculations for visibility, and correctly show as visible when they are visible. Fixed in [#29680](https://github.com/cypress-io/cypress/pull/29680). Fixes [#29605](https://github.com/cypress-io/cypress/issues/29605).
```

2025-01-15 17:39 UTC, MikeMcC399 requested changes
Added several comments in-line

2025-01-15 17:58 UTC, MikeMcC399 commented on docs/app/references/migration-guide.mdx
> +This support is inline with Node.js's support for Linux in 18+.
```suggestion
This support is in line with Node.js's support for Linux in 18+.
```

https://www.merriam-webster.com/dictionary/in%20line%20with

2025-01-15 19:37 UTC, mschile approved these changes

2025-01-15 21:39 UTC, AtofStryker commented on docs/app/references/changelog.mdx
> +- It is no longer possible to make a `fetch` or `XMLHttpRequest` request from the `about:blank` page in Electron (i.e. `cy.window().then((win) => win.fetch('<some-url>'))`). You must use `cy.request`
My guess is this is supposed to be `30394`

2025-01-16 21:16 UTC, merged