docs: add defaultBrowser config option
cypress-io/cypress-documentation pull request #5991
Opened 2024-11-07 20:11 UTC by alexsch01

For https://github.com/cypress-io/cypress/pull/30517

2024-11-13 20:39 UTC, MikeMcC399 reviewed
Wouldn't it make more sense to put this in the https://docs.cypress.io/app/references/configuration#Browser section?

2024-11-13 20:42 UTC, MikeMcC399 reviewed
What about https://docs.cypress.io/app/references/module-api#Options ?

Shouldn't there be an entry there as well?

- (I may have been misled due to the comment in https://github.com/cypress-io/cypress/pull/30517#pullrequestreview-2430146621)

2024-11-13 21:26 UTC, alexsch01 commented
> Wouldn't it make more sense to put this in the https://docs.cypress.io/app/references/configuration#Browser section?

changed, I think that makes sense

2024-11-14 13:04 UTC, MikeMcC399 requested changes
Linting is failing, so 

```shell
npm run lint:fix
```

needs to be run

2024-11-14 22:15 UTC, mschile commented on docs/app/references/configuration.mdx
> +| `defaultBrowser`        | `null`  | The default browser to launch if the "--browser" command line option is not provided. This option only affects the first browser launched; changing this option a
```suggestion
| `defaultBrowser`        | `null`  | The default browser to launch if the "--browser" command line option is not provided. This option only affects the first browser launch; changing this option after the browser is already launched will have no effect.                                                                                                                              |
```

2024-11-14 22:15 UTC, mschile approved these changes

2024-11-14 23:03 UTC, merged